[obs]
type = s3
provider = HuaweiOBS
access_key_id = YOUR_ACCESS_KEY
secret_access_key = YOUR_SECRET_KEYcdm0a0ZQ25389kWTsvJpzZtg3ZKLz12jxHQAyLLN
endpoint = obs.tr-west-1.myhuaweicloud.com
acl = private
bucket_acl = private
